/**
 * Sections for «Сырмақ» — қыз ұзату.
 *
 * Written after reading the first screen of all 22 ұзату and all 30 үйлену
 * тойы templates at toi.com.kz, plus the wedding catalogue at shaqyru24.
 * Three things are true of all 52 of them, and this template is built to be
 * none of them:
 *
 *  - Every single one is a centred vertical poster. Not one breaks the centre
 *    axis, and not one lets a photograph run off an edge. So this one is set
 *    on a left margin throughout, and its artwork bleeds past both edges.
 *  - Ornament is never the primary graphic. It appears as a thin gold
 *    filigree border or an arch, at caption scale. Here ою runs at
 *    architectural scale — a full-width frieze of real syrmaq felt, and
 *    medallions large enough to be cropped by the page.
 *  - The palette is always European bridal: cream and gold, blush, wine,
 *    emerald. This one is taken off a felt carpet instead — undyed wool,
 *    madder, ochre, dark brown — and carries no gold at all.
 *
 * ұзату is an «ақ» rite: ақ дастархан, ақ бата, ақ жол. A dark ground fights
 * that, which is why this stays light even though a dark card would stand out
 * more in a catalogue grid.
 */
import type { ElementSpec, SectionBuilder, SectionContext, SectionResult } from './types';

type Copy = { kz: string; ru: string };
const t = (c: Copy, ctx: SectionContext) => (ctx.locale === 'ru' ? c.ru : c.kz);

/** Photography and the felt frieze. See docs — generated by the owner. */
export const SYRMAQ_ASSETS = {
  hero: '/assets/templates/syrmaq/hero.webp',
  syrmaq: '/assets/templates/syrmaq/ground-syrmaq.webp',
  felt: '/assets/templates/syrmaq/ground-felt.webp',
  story1: '/assets/templates/syrmaq/story-1.webp',
  story2: '/assets/templates/syrmaq/story-2.webp',
  story3: '/assets/templates/syrmaq/story-3.webp',
  venue: '/assets/templates/syrmaq/venue.webp',
  closing: '/assets/templates/syrmaq/closing.webp',
} as const;

/** Shared ою silhouettes — not template-specific, several templates use them. */
export const OYU = {
  medallion: '/assets/templates/oyu-kit/oyu-medallion.png',
  rosette: '/assets/templates/oyu-kit/oyu-rosette.png',
  corner: '/assets/templates/oyu-kit/oyu-corner.png',
  rule: '/assets/templates/oyu-kit/oyu-rule.png',
  band: '/assets/templates/oyu-kit/oyu-band-x10.png',
} as const;

const deep = (ctx: SectionContext) => ctx.theme.accentDeep ?? ctx.theme.accent;

// ---------------------------------------------------------------------------
// Type scale
// ---------------------------------------------------------------------------

/**
 * Sizes are design px on a 390px canvas, so on a 375px phone they render at
 * about 0.96x. Calibrated against the reference services measured at 375px:
 * their names run 89px, section headings 36-42px and body 19.6px. Everything
 * this catalogue shipped before was roughly half that, which is the single
 * biggest reason our templates read as drafts next to theirs.
 */
const T = {
  name: 74,
  heading: 34,
  numeral: 52,
  script: 46,
  body: 16.5,
  caption: 13,
  eyebrow: 11.5,
} as const;

/** Left margin, in percent. The whole template hangs off this one line. */
const M = 8.5;

interface Common {
  x?: number;
  y: number;
  w?: number;
}

function eyebrow(ctx: SectionContext, copy: Copy, at: Common, color?: string): ElementSpec {
  return {
    type: 'text',
    props: {
      x: at.x ?? M,
      y: at.y,
      w: at.w ?? 70,
      h: 'auto',
      text: t(copy, ctx),
      fontFamily: 'Monolog',
      fontSize: T.eyebrow,
      fontWeight: 500,
      color: color ?? ctx.theme.accent,
      textAlign: 'left',
      lineHeight: 1.4,
      letterSpacing: 3.4,
      uppercase: true,
    },
  };
}

function body(ctx: SectionContext, copy: Copy, at: Common): ElementSpec {
  return {
    type: 'text',
    props: {
      x: at.x ?? M,
      y: at.y,
      w: at.w ?? 78,
      h: 'auto',
      text: t(copy, ctx),
      fontFamily: 'Monolog',
      fontSize: T.body,
      fontWeight: 400,
      color: ctx.theme.ink,
      textAlign: 'left',
      lineHeight: 1.72,
      letterSpacing: 0,
    },
  };
}

function heading(ctx: SectionContext, copy: Copy, at: Common, size: number = T.heading): ElementSpec {
  return {
    type: 'heading',
    props: {
      x: at.x ?? M,
      y: at.y,
      w: at.w ?? 76,
      h: 'auto',
      text: t(copy, ctx),
      fontFamily: 'Oranienbaum',
      fontSize: size,
      fontWeight: 400,
      color: ctx.theme.ink,
      textAlign: 'left',
      lineHeight: 1.14,
      letterSpacing: 0,
    },
  };
}

/**
 * Centre a spec that would otherwise sit on the left margin.
 *
 * Used for exactly two sections. `rsvp-form` and `wishes` are shared
 * components whose internals centre themselves in about a dozen hardcoded
 * inline styles, so a left-aligned heading above a centred form reads as a
 * mistake. Making those components configurable would change how every
 * other template in the catalogue looks, which is not a change to make in
 * passing — so the two interactive sections are centred deliberately and
 * the eleven editorial ones stay on the margin.
 */
function centred(spec: ElementSpec): ElementSpec {
  return { ...spec, props: { ...spec.props, x: 8.5, w: 83, textAlign: 'center' } };
}

/** A tinted ою silhouette. One file serves every palette; see ImageElement.tint. */
function oyu(props: {
  src: string;
  x: number;
  y: number;
  w: number;
  h: number;
  color: string;
  rotation?: number;
  fit?: 'cover' | 'contain' | 'fill';
}): ElementSpec['props'] {
  return {
    x: props.x,
    y: props.y,
    w: props.w,
    h: props.h,
    src: props.src,
    tint: props.color,
    objectFit: props.fit ?? 'contain',
    borderRadius: 0,
    ...(props.rotation !== undefined ? { rotation: props.rotation } : {}),
  };
}

// ---------------------------------------------------------------------------
// 1. Hero — a horizontal photograph, not a vertical poster
// ---------------------------------------------------------------------------

/**
 * The opening screen.
 *
 * The photograph runs as a full-bleed horizontal band rather than filling the
 * screen vertically, which is the opposite of all 52 reference cards. That is
 * partly a compositional choice and partly honesty about the picture: what
 * makes the steppe shot work is its width and the emptiness above the
 * horizon, and a vertical crop throws exactly that away.
 *
 * It also fixes the type. The sky in that frame measures #e1e1dd — near
 * white — so white names laid over it would have no contrast at all. The
 * names sit below on the wool instead, in dark ink, at 74px.
 */
export function syrHero(options: { bride?: string } = {}): SectionBuilder {
  return (ctx): SectionResult => {
    const { theme } = ctx;
    const HEIGHT = 754;
    const PHOTO_H = 396;

    const elements: ElementSpec[] = [
      // Photograph. Wider than the page on both sides, feathered at the foot
      // so it dissolves into the wool instead of butting against it.
      {
        type: 'image',
        props: {
          x: -6,
          y: 0,
          w: 118,
          h: PHOTO_H,
          src: SYRMAQ_ASSETS.hero,
          objectFit: 'cover',
          borderRadius: 0,
          maskFade: { bottom: 16 },
          grade: { saturate: 96, contrast: 104 },
          placeholderKey: 'coverPhoto',
        },
        animate: false,
      },

      // Medallion, cropped by the right edge, sitting under the type.
      {
        type: 'image',
        props: oyu({
          src: OYU.medallion,
          x: 63,
          y: 500,
          w: 56,
          h: 218,
          color: 'rgba(154,59,52,0.15)',
        }),
        animate: false,
      },

      eyebrow(ctx, { kz: 'Қыз ұзату', ru: 'Қыз ұзату' }, { y: 428 }),

      {
        type: 'heading',
        props: {
          x: M - 0.5,
          y: 452,
          w: 88,
          h: 'auto',
          text: options.bride ?? 'АЙСҰЛУ',
          fontFamily: 'Oranienbaum',
          fontSize: T.name,
          fontWeight: 400,
          color: theme.ink,
          textAlign: 'left',
          lineHeight: 1.02,
          letterSpacing: 1,
          uppercase: true,
          placeholderKey: 'brideName',
        },
        animate: { type: 'fadeUp', duration: 0.9, delay: 0.1 },
      },

      {
        type: 'divider',
        props: {
          x: M,
          y: 554,
          w: 26,
          h: 2,
          color: deep(ctx),
          thickness: 1.5,
          style: 'solid',
        },
      },

      {
        type: 'text',
        props: {
          x: M,
          y: 574,
          w: 76,
          h: 'auto',
          text: '15 мамыр 2027 · 17:00',
          fontFamily: 'Monolog',
          fontSize: T.caption,
          fontWeight: 500,
          color: theme.muted,
          textAlign: 'left',
          lineHeight: 1.5,
          letterSpacing: 2.4,
          uppercase: true,
          placeholderKey: 'eventDate',
        },
      },
    ];

    return { elements, height: HEIGHT };
  };
}

// ---------------------------------------------------------------------------
// 2. Felt frieze — the one place a real material is shown as itself
// ---------------------------------------------------------------------------

/**
 * A full-width band of the actual syrmaq carpet.
 *
 * This is a photograph of felt, not a drawn texture: the wool fibre and the
 * hand-stitched cord are really there. It also keeps the two ornament systems
 * apart — the carpet has its own red-and-ochre ою, so our black silhouettes
 * never appear within 600px of it.
 */
export function syrFrieze(height = 62): SectionBuilder {
  return (): SectionResult => ({
    elements: [
      {
        type: 'image',
        props: {
          x: -2,
          y: 20,
          w: 104,
          h: height,
          src: SYRMAQ_ASSETS.syrmaq,
          objectFit: 'cover',
          borderRadius: 0,
        },
        animate: false,
      },
    ],
    height: height + 44,
  });
}

// ---------------------------------------------------------------------------
// 3. Invitation
// ---------------------------------------------------------------------------

export function syrInvite(): SectionBuilder {
  return (ctx): SectionResult => {
    const elements: ElementSpec[] = [
      // Rosette bleeding off the right, behind the text.
      {
        type: 'image',
        props: oyu({
          src: OYU.rosette,
          x: 60,
          y: 36,
          w: 64,
          h: 250,
          color: 'rgba(176,124,62,0.14)',
        }),
        animate: false,
      },

      eyebrow(ctx, { kz: 'Құрметті қонақтар', ru: 'Дорогие гости' }, { y: 54 }),

      heading(
        ctx,
        { kz: 'Аяулы қызымыздың\nұзату тойы', ru: 'Ұзату той\nнашей дочери' },
        { y: 84, w: 74 }
      ),

      body(
        ctx,
        {
          kz: 'Ағайын-туыс, бауырлар, құда-жекжат, дос-жаран! Сіздерді аяулы қызымыздың ұзату тойына арналған ақ дастарханымыздың қадірлі қонағы болуға шақырамыз.',
          ru: 'Дорогие родные, близкие и друзья! Приглашаем вас разделить с нами ақ дастархан на ұзату той нашей любимой дочери.',
        },
        { y: 208, w: 80 }
      ),

      {
        type: 'image',
        props: oyu({
          src: OYU.rule,
          x: M,
          y: 366,
          w: 70,
          h: 30,
          color: deep(ctx),
        }),
      },

      eyebrow(ctx, { kz: 'Той иелері', ru: 'Хозяева тоя' }, { y: 418 }, ctx.theme.muted),

      heading(ctx, { kz: 'Серік & Гүлнар', ru: 'Серик & Гулнар' }, { y: 442, w: 78 }, 26),
    ];

    return { elements, height: 512 };
  };
}

// ---------------------------------------------------------------------------
// 4. Өлең — the one place a script face is allowed
// ---------------------------------------------------------------------------

/**
 * A verse, set in Corinthia in madder.
 *
 * Script is rationed on purpose. Every reference card sets its names in
 * calligraphy, so calligraphic names are the one thing that cannot make this
 * template look different. Used once, on a line of poetry, it reads as
 * meaning rather than as decoration.
 */
export function syrOlen(): SectionBuilder {
  return (ctx): SectionResult => ({
    elements: [
      {
        type: 'image',
        props: oyu({
          src: OYU.corner,
          x: 52,
          y: -34,
          w: 62,
          h: 242,
          color: 'rgba(176,124,62,0.20)',
        }),
        animate: false,
      },
      {
        type: 'text',
        props: {
          x: M,
          y: 84,
          w: 84,
          h: 'auto',
          text: t(
            {
              kz: 'Ұясынан ұшқан\nқызғалдағым',
              ru: 'Ұясынан ұшқан\nқызғалдағым',
            },
            ctx
          ),
          fontFamily: 'Corinthia',
          fontSize: T.script,
          fontWeight: 400,
          color: ctx.theme.accent,
          textAlign: 'left',
          lineHeight: 1.35,
          letterSpacing: 0,
        },
      },
      {
        type: 'text',
        props: {
          x: M,
          y: 232,
          w: 60,
          h: 'auto',
          text: t({ kz: 'халық өлеңінен', ru: 'из народной песни' }, ctx),
          fontFamily: 'Monolog',
          fontSize: T.eyebrow,
          fontWeight: 400,
          color: ctx.theme.muted,
          textAlign: 'left',
          lineHeight: 1.4,
          letterSpacing: 2.6,
          uppercase: true,
        },
      },
    ],
    height: 342,
  });
}

// ---------------------------------------------------------------------------
// 5. Story — three photographs on a broken grid
// ---------------------------------------------------------------------------

/**
 * Three objects, placed off-grid and at three different sizes.
 *
 * The reference cards run galleries as an even horizontal strip of equal
 * thumbnails. A 6:1 scale break between the largest and smallest frame is
 * what makes a page look art-directed rather than templated, and it costs
 * nothing but coordinates.
 */
export function syrStory(): SectionBuilder {
  return (ctx): SectionResult => ({
    elements: [
      eyebrow(ctx, { kz: 'Біздің дәстүр', ru: 'Наша традиция' }, { y: 0 }),

      // Large frame, bleeding off the right edge.
      {
        type: 'image',
        props: {
          x: 30,
          y: 36,
          w: 82,
          h: 250,
          src: SYRMAQ_ASSETS.story1,
          objectFit: 'cover',
          borderRadius: 0,
        },
      },
      // Small frame, overlapping it from the left, lower.
      {
        type: 'image',
        props: {
          x: -6,
          y: 214,
          w: 46,
          h: 170,
          src: SYRMAQ_ASSETS.story2,
          objectFit: 'cover',
          borderRadius: 0,
        },
      },
      // Third, right and lower again, smallest.
      {
        type: 'image',
        props: {
          x: 52,
          y: 330,
          w: 40,
          h: 132,
          src: SYRMAQ_ASSETS.story3,
          objectFit: 'cover',
          borderRadius: 0,
        },
      },
      {
        type: 'text',
        props: {
          x: M,
          y: 400,
          w: 40,
          h: 'auto',
          text: t(
            { kz: 'Ақ тілек, ақ бата, ақ жол', ru: 'Ақ тілек, ақ бата, ақ жол' },
            ctx
          ),
          fontFamily: 'Monolog',
          fontSize: T.caption,
          fontWeight: 400,
          color: ctx.theme.muted,
          textAlign: 'left',
          lineHeight: 1.6,
          letterSpacing: 0,
        },
      },
    ],
    height: 520,
  });
}

// ---------------------------------------------------------------------------
// 6. When
// ---------------------------------------------------------------------------

export function syrWhen(options: { targetIso?: string } = {}): SectionBuilder {
  return (ctx): SectionResult => ({
    elements: [
      eyebrow(ctx, { kz: 'Той күні', ru: 'Дата тоя' }, { y: 0 }),
      {
        type: 'heading',
        props: {
          x: M - 0.5,
          y: 26,
          w: 88,
          h: 'auto',
          text: '15.05.2027',
          fontFamily: 'Oranienbaum',
          fontSize: T.numeral,
          fontWeight: 400,
          color: deep(ctx),
          textAlign: 'left',
          lineHeight: 1.05,
          letterSpacing: 0,
          placeholderKey: 'eventDate',
        },
      },
      {
        type: 'text',
        props: {
          x: M,
          y: 100,
          w: 70,
          h: 'auto',
          text: t({ kz: 'сағат 17:00-де', ru: 'в 17:00' }, ctx),
          fontFamily: 'Monolog',
          fontSize: T.body,
          fontWeight: 400,
          color: ctx.theme.ink,
          textAlign: 'left',
          lineHeight: 1.5,
          letterSpacing: 0,
          placeholderKey: 'eventTime',
        },
      },
      {
        type: 'countdown',
        props: {
          x: M,
          y: 156,
          w: 83,
          h: 88,
          targetIso: options.targetIso,
          fontFamily: 'Oranienbaum',
          fontSize: 30,
          color: ctx.theme.ink,
          accentColor: ctx.theme.accent,
          showLabels: true,
        },
      },
      {
        type: 'calendar',
        props: {
          x: M,
          y: 240,
          w: 83,
          h: 300,
          targetIso: options.targetIso,
          fontFamily: 'Monolog',
          fontSize: 14,
          color: ctx.theme.ink,
          accentColor: ctx.theme.accent,
          markStyle: 'fill',
          showMonthTitle: true,
          showWeekdays: true,
        },
      },
    ],
    height: 604,
  });
}

// ---------------------------------------------------------------------------
// 7. Programme
// ---------------------------------------------------------------------------

export function syrProgram(): SectionBuilder {
  return (ctx): SectionResult => ({
    elements: [
      eyebrow(ctx, { kz: 'Бағдарлама', ru: 'Программа' }, { y: 0 }),
      {
        type: 'program',
        props: {
          x: M,
          y: 34,
          w: 83,
          h: 300,
          items: [
            {
              id: 'p1',
              time: '17:00',
              title: t({ kz: 'Қонақтарды қарсы алу', ru: 'Встреча гостей' }, ctx),
            },
            {
              id: 'p2',
              time: '18:00',
              title: t({ kz: 'Ұзату тойының басталуы', ru: 'Начало ұзату тоя' }, ctx),
            },
            {
              id: 'p3',
              time: '20:00',
              title: t({ kz: 'Ақ бата', ru: 'Ақ бата' }, ctx),
            },
            {
              id: 'p4',
              time: '22:00',
              title: t({ kz: 'Қыз қоштасу', ru: 'Қыз қоштасу' }, ctx),
            },
          ],
          fontFamily: 'Monolog',
          bgColor: 'transparent',
          textColor: ctx.theme.ink,
          accentColor: ctx.theme.accent,
          timeColor: deep(ctx),
        },
      },
    ],
    height: 216,
  });
}

// ---------------------------------------------------------------------------
// 8. Dress code — swatches taken straight off the carpet
// ---------------------------------------------------------------------------

export function syrDress(): SectionBuilder {
  return (ctx): SectionResult => {
    const swatches = ['#EDE6D8', '#B07C3E', '#9A3B34', '#6E5B43', '#2A211A'];
    const elements: ElementSpec[] = [
      eyebrow(ctx, { kz: 'Дресс-код', ru: 'Дресс-код' }, { y: 0 }),
      body(
        ctx,
        {
          kz: 'Тойымыздың түстерін ұстанып, сәнді киіммен келуіңізді сұраймыз.',
          ru: 'Просим вас поддержать палитру тоя и прийти в нарядной одежде.',
        },
        { y: 28, w: 76 }
      ),
    ];

    swatches.forEach((fill, i) => {
      elements.push({
        type: 'shape',
        props: {
          x: M + i * 14,
          y: 118,
          w: 11,
          h: 44,
          shape: 'circle',
          fill,
          stroke: i === 0 ? ctx.theme.muted : undefined,
          strokeWidth: i === 0 ? 1 : 0,
        },
        animate: { type: 'fadeUp', duration: 0.5, delay: 0.08 * i },
      });
    });

    return { elements, height: 182 };
  };
}

// ---------------------------------------------------------------------------
// 9. Location
// ---------------------------------------------------------------------------

export function syrLocation(): SectionBuilder {
  return (ctx): SectionResult => ({
    elements: [
      // Mirror of the hero: this photograph bleeds off the LEFT.
      {
        type: 'image',
        props: {
          x: -18,
          y: 0,
          w: 86,
          h: 236,
          src: SYRMAQ_ASSETS.venue,
          objectFit: 'cover',
          borderRadius: 0,
          // The only blue-hour frame in the set. Left alone it reads as a
          // different template's photograph; warmed and desaturated it sits
          // inside the wool palette instead of puncturing it.
          grade: { saturate: 58, brightness: 112, sepia: 32 },
        },
        animate: false,
      },
      eyebrow(ctx, { kz: 'Мекенжай', ru: 'Место' }, { y: 268 }),
      heading(ctx, { kz: '«Салтанат» сарайы', ru: '«Салтанат» сарайы' }, { y: 294, w: 76 }, 28),
      {
        type: 'text',
        props: {
          x: M,
          y: 344,
          w: 74,
          h: 'auto',
          text: t({ kz: 'Астана қаласы, Тәуелсіздік даңғылы 12', ru: 'г. Астана, пр. Тәуелсіздік 12' }, ctx),
          fontFamily: 'Monolog',
          fontSize: T.body,
          fontWeight: 400,
          color: ctx.theme.muted,
          textAlign: 'left',
          lineHeight: 1.6,
          letterSpacing: 0,
          placeholderKey: 'venueAddress',
        },
      },
      {
        type: 'button',
        props: {
          x: M,
          y: 412,
          w: 46,
          h: 48,
          label: t({ kz: 'Картадан ашу', ru: 'Открыть карту' }, ctx),
          action: { kind: 'map' },
          bgColor: ctx.theme.accent,
          textColor: '#FFFFFF',
          fontFamily: 'Monolog',
          fontSize: 14,
          borderRadius: 0,
        },
      },
    ],
    height: 512,
  });
}

// ---------------------------------------------------------------------------
// 10. RSVP
// ---------------------------------------------------------------------------

export function syrRsvp(): SectionBuilder {
  return (ctx): SectionResult => ({
    elements: [
      centred(eyebrow(ctx, { kz: 'Жауабыңызды күтеміз', ru: 'Ждём вашего ответа' }, { y: 0 })),
      centred(heading(ctx, { kz: 'Келесіз бе?', ru: 'Придёте?' }, { y: 26 }, 30)),
      {
        type: 'rsvp-form',
        props: {
          x: M,
          y: 88,
          w: 83,
          h: 380,
          fontFamily: 'Monolog',
          bgColor: 'transparent',
          textColor: ctx.theme.ink,
          accentColor: ctx.theme.accent,
          askPlusOne: true,
          askDietary: false,
          askChildren: false,
        },
      },
    ],
    height: 306,
  });
}

// ---------------------------------------------------------------------------
// 11. Wishes
// ---------------------------------------------------------------------------

export function syrWishes(): SectionBuilder {
  return (ctx): SectionResult => ({
    elements: [
      centred(eyebrow(ctx, { kz: 'Ізгі ниетпен', ru: 'С добрыми пожеланиями' }, { y: 0 })),
      centred(heading(ctx, { kz: 'Тілектер', ru: 'Пожелания' }, { y: 26 }, 30)),
      {
        type: 'wishes',
        props: {
          x: M,
          y: 88,
          w: 83,
          h: 300,
          fontFamily: 'Monolog',
          bgColor: 'transparent',
          textColor: ctx.theme.ink,
          accentColor: ctx.theme.accent,
          reactions: [String.fromCodePoint(0x2764,0xFE0F), String.fromCodePoint(0x1F64F), String.fromCodePoint(0x1F942), String.fromCodePoint(0x1F44F)],
          allowAnonymous: true,
        },
      },
    ],
    height: 300,
  });
}

// ---------------------------------------------------------------------------
// 12. Closing
// ---------------------------------------------------------------------------

export function syrClosing(): SectionBuilder {
  return (ctx): SectionResult => ({
    elements: [
      {
        type: 'image',
        props: {
          x: -6,
          y: 60,
          w: 118,
          h: 400,
          src: SYRMAQ_ASSETS.closing,
          objectFit: 'cover',
          borderRadius: 0,
          maskFade: { top: 14 },
          overlayGradient: {
            from: 'rgba(20,14,10,0.05)',
            to: 'rgba(20,14,10,0.55)',
            angle: 180,
          },
        },
        animate: false,
      },
      {
        type: 'image',
        props: oyu({
          src: OYU.medallion,
          x: 34,
          y: 210,
          w: 32,
          h: 125,
          color: 'rgba(245,239,226,0.9)',
        }),
      },
      {
        type: 'text',
        props: {
          x: M,
          y: 366,
          w: 83,
          h: 'auto',
          text: t({ kz: 'Сіздерді күтеміз', ru: 'Ждём вас' }, ctx),
          fontFamily: 'Oranienbaum',
          fontSize: 32,
          fontWeight: 400,
          color: ctx.theme.onPhoto,
          textAlign: 'center',
          lineHeight: 1.2,
          letterSpacing: 1,
        },
      },
    ],
    height: 470,
  });
}
